// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBtE1s7P-5cmZLUwnYsAHqjRSWddeJLxg',
    appId: '1:958135602892:web:d886d6b72be256dd92fc69',
    messagingSenderId: '958135602892',
    projectId: 'customer-feedback-analytic',
    authDomain: 'customer-feedback-analytic.firebaseapp.com',
    storageBucket: 'customer-feedback-analytic.appspot.com',
    measurementId: 'G-G56QWQ55V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5CL98L8lCXuLKts0nXezHnssG5lyEemI',
    appId: '1:958135602892:android:e5bfe700ad2cdd5292fc69',
    messagingSenderId: '958135602892',
    projectId: 'customer-feedback-analytic',
    storageBucket: 'customer-feedback-analytic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoElrjp6tgkuNRvGcRSe0W-keVurdyz9Y',
    appId: '1:958135602892:ios:b0770c95e30934ac92fc69',
    messagingSenderId: '958135602892',
    projectId: 'customer-feedback-analytic',
    storageBucket: 'customer-feedback-analytic.appspot.com',
    iosClientId: '958135602892-486fbtlfl8ntsm8ms8ndol1lqrf3ab2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.customerFeedbackAnalysis',
  );
}
